BEGIN;

ALTER TABLE findings
ADD COLUMN IF NOT EXISTS cvss_v3_score DECIMAL(3,1),
ADD COLUMN IF NOT EXISTS cvss_v3_vector TEXT,
ADD COLUMN IF NOT EXISTS primary_url TEXT,
ADD COLUMN IF NOT EXISTS layer_digest TEXT,
ADD COLUMN IF NOT EXISTS layer_index INTEGER;

COMMIT;
