BEGIN;

ALTER TABLE scans
ADD COLUMN IF NOT EXISTS critical_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS high_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS medium_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS low_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS unknown_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS duration_ms INTEGER,
ADD COLUMN IF NOT EXISTS image_os TEXT,
ADD COLUMN IF NOT EXISTS image_arch TEXT,
ADD COLUMN IF NOT EXISTS image_size BIGINT,
ADD COLUMN IF NOT EXISTS layer_count INTEGER,
ADD COLUMN IF NOT EXISTS base_image TEXT;

COMMIT;
